### ISSUE TITLE
Improve individual page footer spacing for readability

### ISSUE THREAD

**Issue by smit1678** [hotosm/hugo-book#2]
Especially when there is short content, the footer information (edit and last modified) is quite close to the content and spacing/layout could be improved to make easier to read. 

This may be because we're using the red link style for now but flagging this for a future review/improvement. 

<img width="1424" alt="HOT Toolbox 2019-04-29 11-08-57" src="https://user-images.githubusercontent.com/796838/56876305-9af2de00-6a70-11e9-9a55-040d547c870a.png">

**Comment by russbiggs** [comment]
I agree a bit more bottom padding would help separate the github links from the main content

**Comment by russbiggs** [comment]
I've added some padding that I think improves readability if there are more changes reopen and we can review.
